import type { WayfindingEvent, WayfindingBusiness } from './types'

export const CARNAVAL_EVENT: WayfindingEvent = {
  id: 'static-carnaval',
  slug: 'carnaval',
  name: 'Carnaval',
  eyebrow: 'SomerStreets',
  organizer_name: 'East Somerville Main Streets + Somerville Arts Council',
  organizer_logo_url: null,
  date_primary: '2026-06-07',
  date_rain: '2026-06-14',
  time_start: '14:00',
  time_end: '18:00',
  accent_color: '#D81B60',
  corridor_geojson: {
    type: 'LineString',
    coordinates: [
      [-71.0780, 42.3858],
      [-71.0785, 42.3860],
      [-71.0795, 42.3863],
      [-71.0808, 42.3866],
      [-71.0820, 42.3870],
      [-71.0830, 42.3873],
      [-71.0840, 42.3876],
      [-71.0845, 42.3878],
      [-71.0850, 42.3880],
      [-71.0855, 42.3883],
      [-71.0860, 42.3889],
      [-71.0865, 42.3891],
      [-71.0870, 42.3895],
      [-71.0875, 42.3898],
    ],
  },
  center_lat: 42.3878,
  center_lng: -71.0835,
  default_zoom: 16,
  locales: ['en', 'es', 'pt'],
  attribution: 'Wayfinding by Green Streets Initiative',
  is_rain_date: false,
  is_cancelled: false,
  is_published: true,
  admin_token: null,
  created_at: '2026-05-18T00:00:00Z',
}

export const CARNAVAL_RESTAURANTS: WayfindingBusiness[] = [
  { id: 'r1', event_id: 'static-carnaval', name: 'La Brasa', category: 'Restaurants', description: 'Wood-fired, globally inspired dishes & cocktails.', lat: 42.3876847, lng: -71.0845514, address: '124 Broadway', website_url: 'https://www.labrasasomerville.com', google_place_id: null, show_on_map: true, pin_color: null },
  { id: 'r2', event_id: 'static-carnaval', name: 'Fat Hen', category: 'Restaurants', description: 'Cozy Italian serving bowls of pasta & braised meats, plus fine wine.', lat: 42.38791, lng: -71.084638, address: null, website_url: null, google_place_id: 'ChIJf_M5Y9pw44kRuMmmh5GnXUY', show_on_map: true, pin_color: null },
  { id: 'r3', event_id: 'static-carnaval', name: 'Taqueria Montecristo', category: 'Restaurants', description: 'Authentic Taqueria, Mexican and Salvadorean specialties.', lat: 42.3880836, lng: -71.0850222, address: '146 Broadway', website_url: 'https://montecristorestaurantsomerville.com', google_place_id: 'ChIJVVr8e9pw44kR5ycgfoFBlhU', show_on_map: true, pin_color: null },
  { id: 'r4', event_id: 'static-carnaval', name: 'Gauchao Brazilian Cuisine', category: 'Restaurants', description: 'Corner churrascaria with a buffet, fire-roasted meats & Brazilian specialties.', lat: 42.3874654, lng: -71.08344, address: null, website_url: null, google_place_id: 'ChIJEalB9tpw44kRIR4EqysYXB8', show_on_map: true, pin_color: null },
  { id: 'r5', event_id: 'static-carnaval', name: 'Rincon Mexicano Somerville', category: 'Restaurants', description: 'Authentic Mexican cuisine.', lat: 42.387646, lng: -71.082899, address: '99 Broadway', website_url: 'https://www.rinconmexicanosomerville.com', google_place_id: 'ChIJYbgbVNpw44kRFV41qqw3mPw', show_on_map: true, pin_color: null },
  { id: 'r6', event_id: 'static-carnaval', name: 'Blessing Caribbean', category: 'Restaurants', description: 'Haitian and Caribbean Cuisine, Creole Griot.', lat: 42.3875178, lng: -71.0823981, address: '89 Broadway', website_url: null, google_place_id: 'ChIJsRBOVdpw44kRaJlfIaYcIbM', show_on_map: true, pin_color: null },
  { id: 'r7', event_id: 'static-carnaval', name: "Recino's Cafe", category: 'Restaurants', description: 'Baked goods, beverages, and pupusas.', lat: 42.3874485, lng: -71.0822552, address: '85 Broadway', website_url: null, google_place_id: 'ChIJISwBq9tw44kRA4Ci9wB947w', show_on_map: true, pin_color: null },
  { id: 'r8', event_id: 'static-carnaval', name: "Vinny's Ristorante", category: 'Restaurants', description: null, lat: 42.3868797, lng: -71.0816743, address: '76 Broadway', website_url: 'https://www.vinnysatnight.com/', google_place_id: 'ChIJ4RxWD9tw44kRfnBBHjLukwo', show_on_map: true, pin_color: null },
  { id: 'r9', event_id: 'static-carnaval', name: 'Taco Loco Mexican Grill', category: 'Restaurants', description: 'Counter-serve burritos, taco combos, pupusas.', lat: 42.386342, lng: -71.0796774, address: '44 Broadway', website_url: null, google_place_id: 'ChIJtbLSfNtw44kR25KofPDZl3M', show_on_map: true, pin_color: null },
  { id: 'r10', event_id: 'static-carnaval', name: 'Fasika Ethiopian Restaurant', category: 'Restaurants', description: 'Hands-on Ethiopian dining at traditional wicker tables, plus a full bar.', lat: 42.3883488, lng: -71.0848299, address: '145 Broadway', website_url: 'https://www.fasikaethiopian.com', google_place_id: 'ChIJrxxCcNpw44kRXOPPMg8myZM', show_on_map: true, pin_color: null },
  { id: 'r11', event_id: 'static-carnaval', name: 'Lotus Xpress', category: 'Restaurants', description: 'Sushi, curries & noodle dishes.', lat: 42.3889385, lng: -71.0859397, address: '167 Broadway', website_url: 'https://www.lotusxpress.com', google_place_id: 'ChIJz2le8vh244kREBSYnYwT1Kk', show_on_map: true, pin_color: null },
  { id: 'r12', event_id: 'static-carnaval', name: "Casey's", category: 'Restaurants', description: 'Pizza, sandwiches & bar bites.', lat: 42.3890827, lng: -71.0862535, address: '173 Broadway', website_url: 'https://www.caseyssomerville.com', google_place_id: 'ChIJIWIKl9Bw44kRqrcJvGf4L-w', show_on_map: true, pin_color: null },
  { id: 'r13', event_id: 'static-carnaval', name: 'Maya Sol Mexican Grill', category: 'Restaurants', description: 'Mexican classics & Salvadoran pupusas.', lat: 42.3891326, lng: -71.0865165, address: '179 Broadway', website_url: 'https://www.mayasolmexicangrill.com', google_place_id: 'ChIJ5dyPltBw44kRfHg2YgGDaHQ', show_on_map: true, pin_color: null },
  { id: 'r14', event_id: 'static-carnaval', name: 'Louies', category: 'Restaurants', description: null, lat: 42.389559, lng: -71.0870902, address: null, website_url: null, google_place_id: 'ChIJabfQ8dxw44kRbQGS-fA7VwM', show_on_map: true, pin_color: null },
  { id: 'r15', event_id: 'static-carnaval', name: 'Pastelaria Vitoria Broadway', category: 'Restaurants', description: 'Brazilian Fast Food.', lat: 42.3890312, lng: -71.0873334, address: '192 Broadway', website_url: null, google_place_id: 'ChIJ1WFe6dBw44kRJUBchSYYOwQ', show_on_map: true, pin_color: null },
  { id: 'r16', event_id: 'static-carnaval', name: 'Mount Vernon Restaurant & Pub', category: 'Restaurants', description: null, lat: 42.385929, lng: -71.0782028, address: '14 Broadway', website_url: 'https://www.mtvernonsomerville.com', google_place_id: 'ChIJ0feWktxw44kRMPIGmSD8rU0', show_on_map: true, pin_color: null },
  { id: 'r17', event_id: 'static-carnaval', name: 'Friends Pizza', category: 'Restaurants', description: 'Pizzas, burgers, sandwiches, salads.', lat: 42.386917, lng: -71.086905, address: '38 Cross St', website_url: 'https://www.friendspizzamenu.com', google_place_id: 'ChIJSwOsatBw44kRxu36VKC2rNc', show_on_map: true, pin_color: null },
  { id: 'r18', event_id: 'static-carnaval', name: 'Taqueria Tapatio', category: 'Restaurants', description: 'Mexican Restaurant.', lat: 42.3870327, lng: -71.0821241, address: '82 Broadway', website_url: null, google_place_id: 'ChIJZWCrANtw44kRXWBHooFaO1k', show_on_map: true, pin_color: null },
  { id: 'r19', event_id: 'static-carnaval', name: 'Rei Da Picanha', category: 'Restaurants', description: 'Brazilian Steakhouse, burgers, and hot subs.', lat: 42.3881068, lng: -71.0841152, address: '129 Broadway', website_url: null, google_place_id: 'ChIJoa_wZtpw44kR3hcF6YMTo8o', show_on_map: true, pin_color: null },
  { id: 'r20', event_id: 'static-carnaval', name: 'Ola Cafe', category: 'Restaurants', description: 'Cafe with coffee, pastries, sandwiches, fresh OJ.', lat: 42.3875394, lng: -71.083918, address: '112 Broadway', website_url: 'https://www.olacafesomerville.com', google_place_id: 'ChIJ8Z7uX9pw44kRHcApbk0KJWE', show_on_map: true, pin_color: null },
  { id: 'r21', event_id: 'static-carnaval', name: 'Los Paisanos Restaurant', category: 'Restaurants', description: 'Mexican Dishes.', lat: 42.386576, lng: -71.080744, address: null, website_url: null, google_place_id: 'ChIJ2cSvc9tw44kRUKnF29-Q3bo', show_on_map: true, pin_color: null },
  { id: 'r22', event_id: 'static-carnaval', name: "Buddy's", category: 'Restaurants', description: 'Small diner.', lat: 42.3813466, lng: -71.0868865, address: null, website_url: null, google_place_id: 'ChIJT1qRSc9w44kR9rjagY522fU', show_on_map: true, pin_color: null },
  { id: 'r23', event_id: 'static-carnaval', name: "Oliveira's Steak House", category: 'Restaurants', description: 'Brazilian Steakhouse, rodizio style.', lat: 42.3807928, lng: -71.0869645, address: null, website_url: null, google_place_id: 'ChIJO03Gtchw44kRaJm0taIIUvk', show_on_map: true, pin_color: null },
  { id: 'r24', event_id: 'static-carnaval', name: 'Royal Pizza & Subs', category: 'Restaurants', description: 'Pizza and Subs.', lat: 42.3820859, lng: -71.0820693, address: null, website_url: null, google_place_id: 'ChIJdXDrUcRw44kR_RJR5kDwKUs', show_on_map: true, pin_color: null },
  { id: 'r25', event_id: 'static-carnaval', name: "Michael's Bar", category: 'Restaurants', description: 'Cheap drinks, fun atmosphere, local hangout.', lat: 42.3815692, lng: -71.085876, address: null, website_url: null, google_place_id: 'ChIJE_7PW89w44kR-KWwQjrAJJw', show_on_map: true, pin_color: null },
]
