import type { Metadata } from 'next'
import Link from 'next/link'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import ShareKit from './ShareKit'

export const metadata: Metadata = {
  title: 'Share Shift Your Summer | Green Streets Initiative',
  description:
    'Help grow the challenge — share Shift Your Summer with your team, your neighbors, or your friends.',
}

const CHALLENGE_BASE_URL = 'https://gogreenstreets.org/events/shift-your-summer'

// Whitelist for ?ref= passthrough. Referral codes are short alphanumeric tokens
// generated by the Shift app; reject anything else so we don't echo arbitrary
// query strings back into share blurbs.
function sanitizeRef(value: string | string[] | undefined): string | null {
  const raw = Array.isArray(value) ? value[0] : value
  if (!raw) return null
  if (!/^[A-Za-z0-9_-]{1,32}$/.test(raw)) return null
  return raw
}

export default async function SharePage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>
}) {
  const params = await searchParams
  const refCode = sanitizeRef(params.ref)
  const shareUrl = refCode
    ? `${CHALLENGE_BASE_URL}?ref=${refCode}`
    : CHALLENGE_BASE_URL

  const blurb = `Join Shift Your Summer — a free 8-week challenge (June 15 – Aug 15) where every walk, bike ride, and transit trip is an entry to win. The Shift app tracks your trips automatically. Build streaks, climb the leaderboard, and compete for prizes from Apollo Scooters, Quad Lock, Kryptonite, and more. Every trip earns you an entry. Join here: ${shareUrl}`

  const emailSubject = 'Join me for Shift Your Summer'
  const emailBody = blurb

  return (
    <>
      <Nav />
      <main className="bg-[#191A2E] text-white" style={{ paddingTop: '60px' }}>
        <section className="px-8 py-16 md:py-20">
          <div className="mx-auto max-w-[680px]">
            <Link
              href="/events/shift-your-summer"
              className="mb-8 inline-flex items-center gap-1.5 text-sm text-white/75 transition-colors hover:text-white"
            >
              &larr; Back to Shift Your Summer
            </Link>

            <h1 className="mb-4 font-display text-[clamp(2rem,4vw,2.75rem)] font-extrabold leading-[1.1] tracking-tight text-white">
              Share Shift Your Summer
            </h1>
            <p className="mb-10 text-[1.0625rem] leading-[1.65] text-white/85">
              Help us grow the challenge. Share with your team, your neighbors, or your friends — participants are eligible for prizes from brands like Apollo Scooters, Quad Lock, and Kryptonite just by walking, biking, and taking transit this summer.
            </p>

            <ShareKit
              shareUrl={shareUrl}
              blurb={blurb}
              emailSubject={emailSubject}
              emailBody={emailBody}
              hasReferralCode={refCode !== null}
            />

            <div className="mt-10 rounded-[14px] border border-white/[0.08] bg-white/[0.04] p-6">
              <p className="mb-2 text-xs font-bold uppercase tracking-widest text-white/75">
                Print or post the flyer
              </p>
              <p className="mb-4 text-sm leading-[1.6] text-white/85">
                A one-page flyer that auto-updates with the latest sponsors and prizes. Print it for your office, classroom, or community board.
              </p>
              <Link
                href="/events/shift-your-summer/flyer"
                className="inline-flex items-center gap-2 rounded-full bg-[#BAF14D] px-5 py-2.5 text-sm font-bold text-[#191A2E] transition-opacity hover:opacity-85"
              >
                Open the printable flyer &rarr;
              </Link>
            </div>

            <div className="mt-6 rounded-[14px] border border-white/[0.08] bg-white/[0.04] p-6">
              <p className="mb-2 text-xs font-bold uppercase tracking-widest text-white/75">
                For employers
              </p>
              <p className="mb-4 text-sm leading-[1.6] text-white/85">
                Want your own team leaderboard, branded challenge, and impact reporting?
              </p>
              <Link
                href="/shift/employers"
                className="inline-flex items-center gap-2 text-sm font-semibold text-[#BAF14D] hover:opacity-85"
              >
                Learn about the employer platform &rarr;
              </Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
