import type { Metadata } from 'next'
import Link from 'next/link'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import { PILL } from '@/components/org/Section'
import ShareKit from './ShareKit'

export const metadata: Metadata = {
  title: 'Share Shift Your Summer | Green Streets Initiative',
  description:
    'Help grow the challenge — share Shift Your Summer with your team, your neighbors, or your friends.',
}

const CHALLENGE_BASE_URL = 'https://www.gogreenstreets.org/events/shift-your-summer'

// Whitelist for ?ref= passthrough. Referral codes are short alphanumeric tokens
// generated by the Shift app; reject anything else so we don't echo arbitrary
// query strings back into share blurbs.
function sanitizeRef(value: string | string[] | undefined): string | null {
  const raw = Array.isArray(value) ? value[0] : value
  if (!raw) return null
  if (!/^[A-Za-z0-9_-]{1,32}$/.test(raw)) return null
  return raw
}

export default async function SharePage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>
}) {
  const params = await searchParams
  const refCode = sanitizeRef(params.ref)
  const shareUrl = refCode
    ? `${CHALLENGE_BASE_URL}?ref=${refCode}`
    : CHALLENGE_BASE_URL

  const blurb = `Join Shift Your Summer — a free 8-week challenge (June 15 – Aug 15) where every walk, bike ride, and transit trip is an entry to win. The Shift app tracks your trips automatically. Build streaks, climb the leaderboard, and compete for prizes from Segway, Quad Lock, Kryptonite, and more. Every trip counts as an entry. Join here: ${shareUrl}`

  const emailSubject = 'Join me for Shift Your Summer'
  const emailBody = blurb

  return (
    <>
      <Nav variant="light" />
      <main className="bg-cream text-navy" style={{ paddingTop: '60px' }}>
        <section className="px-6 py-8 lg:px-8 lg:py-10">
          <div className="mx-auto max-w-[680px]">
            <Link
              href="/events/shift-your-summer"
              className="mb-8 inline-flex items-center gap-1.5 text-[15px] font-semibold text-forest underline-offset-4 hover:underline"
            >
              &larr; Back to Shift Your Summer
            </Link>

            <h1 className="mb-4 font-serif text-[clamp(2.5rem,6vw,4.25rem)] font-normal leading-[1.02] tracking-[-0.01em] text-navy">
              Share Shift Your Summer
            </h1>
            <p className="mb-10 text-[1.0625rem] leading-[1.7] text-ink-soft">
              Help us grow the challenge. Share with your team, your neighbors, or your friends — participants are eligible for prizes from brands like Segway, Quad Lock, and Kryptonite just by walking, biking, and taking transit this summer.
            </p>

            <ShareKit
              shareUrl={shareUrl}
              blurb={blurb}
              emailSubject={emailSubject}
              emailBody={emailBody}
              hasReferralCode={refCode !== null}
            />

            <div className="mt-10 rounded-[14px] border border-navy/10 bg-white p-6">
              <p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-forest">
                Print or post the flyer
              </p>
              <p className="mb-4 text-[15px] leading-relaxed text-ink-soft">
                A one-page flyer that auto-updates with the latest sponsors and prizes. Print it for your office, classroom, or community board.
              </p>
              <Link
                href="/events/shift-your-summer/flyer"
                className={PILL}
              >
                Open the printable flyer &rarr;
              </Link>
            </div>

            <div className="mt-6 rounded-[14px] border border-navy/10 bg-white p-6">
              <p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-forest">
                For employers
              </p>
              <p className="mb-4 text-[15px] leading-relaxed text-ink-soft">
                Want your own team leaderboard, branded challenge, and impact reporting?
              </p>
              <Link
                href="/shift/employers"
                className="inline-flex items-center gap-2 text-[15px] font-semibold text-forest underline-offset-4 hover:underline"
              >
                Learn about the employer platform &rarr;
              </Link>
            </div>
          </div>
        </section>
      </main>
      <Footer variant="light" />
    </>
  )
}
